name: WeChat Robot
on:
  schedule:
    - cron: '30 15 * * 1-5' # 每天的 15:30 在周一到周五运行
jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Send message
        run: node wechatRobot.js