name: WeChat Robot
on:
  push:
    branches:
      - main
  schedule:
    - cron: "40 2 * * 1-5" # 每天的 10:10 在周一到周五运行
jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Send message
        run: node wechatRobot.js
